[phases.setup]
nixPkgs = ["python311", "chromium", "nss", "nspr", "atk", "at-spi2-atk", "cups", "libdrm", "libxkbcommon", "libXcomposite", "libXdamage", "libXfixes", "libXrandr", "gbm", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright && playwright install chromium"
]

[start]
cmd = "python3 app.py"
